# Autogenerated file containing the functions executed by the nodes.

def cntr(num_in, cur_cnt, firecounter, phase):

    if num_in[0] == 9:
        new_cnt = [cur_cnt[0] + 1]
    else:
        new_cnt = [cur_cnt[0]]

    return (new_cnt, new_cnt)

def prod(firecounter, phase):
    return [firecounter % 16]

def cnsmr(cnt_in, firecounter, phase):
    return []

